// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TailTranslate",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "TailTranslate",
            targets: ["AppModule"],
            bundleIdentifier: "com.Theodore-Utomo.TailTranslate",
            teamIdentifier: "DK8T7X4Q5B",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .weights),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.pictureFolder, mode: .readOnly),
                .fileAccess(.moviesFolder, mode: .readOnly),
                .camera(purposeString: "This app uses camera to take photos or videos of pets"),
                .photoLibrary(purposeString: "This app uses photo library to analyze photos or videos of pets")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)